language: swift
osx_image: xcode9.3beta
script:
  - xcodebuild -scheme EventBus -project EventBus.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.3' build test
